export type RootStackParamList = {
  Home: undefined;
  AddWineType: undefined;
  BasicInfo: { guidedSessionId?: string; flightWineIndex?: number } | undefined;
  ScanLabel: undefined;
  WineStyle: undefined;
  LookColor: undefined;
  LookDetails: { color: string; colorHex: string; colorSubtitle: string };
  SmellMain: undefined;
  SmellFruitType: undefined;
  SmellFruitDetail: { fruitType: string };
  SmellHerbsSpices: undefined;
  SmellHerbSpiceDetail: { category: 'Herbs' | 'Spices' };
  SmellOutdoorOther: { category: 'Outdoor' | 'Other' };
  Taste: undefined;
  Think: { guidedSessionId?: string } | undefined;
  MyTastings: undefined;
  TastingCalendar: undefined;
  WineDetail: { wineId: string };
  WineTastingGuide: undefined;
  MyProfile: undefined;
  WineryCheckIn: undefined;
  WinerySearch: undefined;
  WineryDetail: { wineryId: string };
  TastingFlightDetail: { flightId: string; wineryId: string };
  GuidedSession: { sessionId: string };
  MyFlights: undefined;
  CompletedFlightDetail: { sessionId: string };
};
